# Generated by Django 5.0.3 on 2024-09-18 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensesType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=22,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateTimeField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.expensestype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=100)),
                ("shortcut", models.CharField(max_length=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=15)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceMoneyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=22),
                ),
                ("amount_paid", models.DecimalField(decimal_places=4, max_digits=22)),
                ("assigned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enventory.invoice",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseMoneyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=22),
                ),
                ("amount_paid", models.DecimalField(decimal_places=4, max_digits=22)),
                ("assigned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.expense",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundReturnInnMoneyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=22),
                ),
                ("amount_paid", models.DecimalField(decimal_places=4, max_digits=22)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("loose_status", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "return_inn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enventory.returninn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundReturnOutMoneyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=22),
                ),
                ("amount_paid", models.DecimalField(decimal_places=4, max_digits=22)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("loose_status", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "return_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enventory.returnout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleTransaction",
            fields=[
                ("recipt_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "change",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                (
                    "change_given",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                ("buyer_name", models.CharField(default="", max_length=100)),
                ("buyer_tin", models.CharField(default="", max_length=100)),
                ("buyer_vat", models.CharField(default="", max_length=100)),
                ("buyer_address", models.CharField(default="", max_length=100)),
                ("buyer_tel", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("open_state", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selling_price", models.DecimalField(decimal_places=4, max_digits=22)),
                ("VAT", models.DecimalField(decimal_places=4, max_digits=22)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=22)),
                (
                    "buying_unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                ("quantity", models.IntegerField()),
                (
                    "used_batches",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
                (
                    "used_batch_quantities",
                    models.CharField(
                        blank=True, default="", max_length=3000, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="enventory.stock",
                    ),
                ),
                (
                    "sale_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.saletransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptMoneyPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=22),
                ),
                ("amount_paid", models.DecimalField(decimal_places=4, max_digits=22)),
                (
                    "change",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                (
                    "change_given",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("loose_status", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "sale_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.saletransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VATCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
