# Generated by Django 5.0.3 on 2025-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_sale_total_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_returned',
            field=models.IntegerField(),
        ),
    ]
