# Generated by Django 5.0.3 on 2026-04-23 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_sale_quantity_alter_sale_total_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 5, 56, 18, 729658, tzinfo=datetime.timezone.utc)),
        ),
    ]
