# Generated by Django 5.0.3 on 2026-04-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_expensemoneyportion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemoneyportion',
            name='date',
        ),
    ]
