# Generated by Django 5.0.3 on 2026-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_expensemoneyportion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestype',
            name='reoccurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='reoccurring_interval',
            field=models.CharField(default='NONE', max_length=30),
        ),
    ]
