# Generated by Django 5.0.3 on 2026-04-24 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_expensestype_reoccurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 13, 14, 14, 163449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 13, 14, 14, 162353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 13, 14, 14, 161243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 13, 14, 14, 162353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 13, 14, 14, 162353, tzinfo=datetime.timezone.utc)),
        ),
    ]
