# Generated by Django 5.0.3 on 2026-04-25 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_expensemoneyportion_date_invoicemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 7, 2, 35, 712252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 7, 2, 35, 711155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 7, 2, 35, 711155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 7, 2, 35, 712252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 7, 2, 35, 712252, tzinfo=datetime.timezone.utc)),
        ),
    ]
