# Generated by Django 5.0.3 on 2026-04-30 08:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0008_returninn_credit_note'),
        ('payments', '0015_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundreturninnmoneyportion',
            name='return_inn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enventory.returninn'),
        ),
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 36, 56, 966996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 36, 56, 965885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 36, 56, 965885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 36, 56, 966996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 36, 56, 966996, tzinfo=datetime.timezone.utc)),
        ),
    ]
