# Generated by Django 5.0.3 on 2026-04-30 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 9, 4, 43, 400744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 9, 4, 43, 399744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 9, 4, 43, 398744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 9, 4, 43, 399744, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 9, 4, 43, 399744, tzinfo=datetime.timezone.utc)),
        ),
    ]
