# Generated by Django 5.0.3 on 2026-05-01 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundreturninnmoneyportion',
            name='return_inn',
        ),
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 7, 47, 56, 486842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 7, 47, 56, 485748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 7, 47, 56, 485748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 7, 47, 56, 486842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 7, 47, 56, 486842, tzinfo=datetime.timezone.utc)),
        ),
    ]
