# Generated by Django 5.0.3 on 2026-05-02 05:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_refundreturninnmoneyportion_return_inn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 5, 16, 39, 583240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 5, 16, 39, 583240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 5, 16, 39, 583240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 5, 16, 39, 583240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 5, 16, 39, 583240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=4, max_digits=22)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField()),
                ('payment_for', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('payment_for_id', models.DecimalField(decimal_places=0, max_digits=15)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('change_given', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('notes', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentmethod')),
            ],
        ),
    ]
