# Generated by Django 5.0.3 on 2026-05-06 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='loose_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 20, 34, 685273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 20, 34, 684273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 20, 34, 684273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 20, 34, 684273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 20, 34, 685273, tzinfo=datetime.timezone.utc)),
        ),
    ]
