# Generated by Django 5.0.3 on 2026-05-06 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_payment_loose_status_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='expensemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 43, 14, 623940, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoicemoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 43, 14, 622435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receiptmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 43, 14, 622435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturninnmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 43, 14, 623435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refundreturnoutmoneyportion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 3, 43, 14, 623435, tzinfo=datetime.timezone.utc)),
        ),
    ]
