# Generated by Django 5.0.3 on 2026-05-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemoneyportion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoicemoneyportion',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicemoneyportion',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='receiptmoneyportion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiptmoneyportion',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='receiptmoneyportion',
            name='sale_transaction',
        ),
        migrations.RemoveField(
            model_name='refundreturninnmoneyportion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='refundreturninnmoneyportion',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='refundreturninnmoneyportion',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='refundreturnoutmoneyportion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='refundreturnoutmoneyportion',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='refundreturnoutmoneyportion',
            name='return_out',
        ),
        migrations.DeleteModel(
            name='ExpenseMoneyPortion',
        ),
        migrations.DeleteModel(
            name='InvoiceMoneyPortion',
        ),
        migrations.DeleteModel(
            name='ReceiptMoneyPortion',
        ),
        migrations.DeleteModel(
            name='RefundReturnInnMoneyPortion',
        ),
        migrations.DeleteModel(
            name='RefundReturnOutMoneyPortion',
        ),
    ]
