# Generated by Django 5.0.3 on 2026-05-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customeraccount_created_by_branch_and_more'),
        ('payments', '0025_remove_invoicemoneyportion_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='expensestype',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='vatcode',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
