# Generated by Django 5.0.3 on 2026-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_vatcode_zimra_tax_id_paymentmethod_zimra_money_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='zimra_money_type_text',
            field=models.CharField(blank=True, default='Cash', max_length=10, null=True),
        ),
    ]
