# Generated by Django 5.0.3 on 2026-06-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_paymentmethod_zimra_money_type_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='buyer_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
