# Generated by Django 5.0.3 on 2026-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_saletransaction_buyer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_tel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_tin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='buyer_vat',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
