# Generated by Django 5.0.3 on 2026-07-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_alter_saletransaction_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcode',
            name='zimra_tax_id',
            field=models.IntegerField(blank=True, help_text='ZIMRA IntTaxID: 1=Exempt, 2=Zero%, 3=15%, 4=15.5%', null=True),
        ),
    ]
