# Generated by Django 5.0.3 on 2026-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_alter_vatcode_zimra_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatcode',
            name='default_hs_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
