# Generated by Django 5.0.3 on 2026-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_vatcode_default_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcode',
            name='default_hs_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
