# Generated by Django 5.0.3 on 2025-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enventory', '0003_alter_stock_reorder_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/makes/')),
            ],
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompatabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_type', models.CharField(max_length=50)),
                ('is_compatible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.carmake')),
                ('car_transmission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge_base.cartransmission')),
            ],
            options={
                'unique_together': {('make', 'model', 'year', 'car_transmission')},
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.carmodel')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enventory.stock')),
                ('compatibility_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.compatabilitytype')),
            ],
            options={
                'verbose_name_plural': 'Compatibilities',
                'unique_together': {('car_part', 'car_model')},
            },
        ),
    ]
