# Generated by Django 5.0.3 on 2025-05-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompatabilityType',
            new_name='CompatibilityType',
        ),
    ]
