# Generated by Django 5.0.3 on 2025-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_rename_compatabilitytype_compatibilitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='make',
            field=models.CharField(max_length=50),
        ),
    ]
