# Generated by Django 5.0.3 on 2025-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_carmake_make'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('engine_number', 'make', 'model', 'year', 'car_transmission')},
        ),
    ]
