# Generated by Django 5.0.3 on 2024-09-18 00:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone_number", models.CharField(max_length=30)),
                ("address", models.TextField(max_length=255)),
                ("roles", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration_name", models.CharField(max_length=30)),
                ("company_name", models.CharField(max_length=30)),
                ("address", models.TextField(blank=True, max_length=255, null=True)),
                ("tel", models.CharField(max_length=90)),
                ("tin_number", models.CharField(max_length=30)),
                ("prz_number", models.CharField(max_length=30)),
                ("vat_number", models.CharField(max_length=30)),
                ("invoice_number_prefix", models.CharField(max_length=30)),
                ("bank_1_bank_name", models.CharField(max_length=30)),
                ("bank_1_account_name", models.CharField(max_length=30)),
                ("bank_1_name_nostro", models.CharField(max_length=30)),
                ("bank_1_name_zig", models.CharField(max_length=30)),
                ("company_registration", models.CharField(max_length=30)),
                ("email", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "thank_you_message",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "online_update_minute_intervals",
                    models.DecimalField(decimal_places=0, default=5, max_digits=10),
                ),
                (
                    "expiration_warning",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                (
                    "pagination_slice_leangth",
                    models.DecimalField(decimal_places=0, default=20, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "subscription_expiration_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("hosting_email", models.CharField(default="", max_length=100)),
                (
                    "hosting_email_password",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "notification_receiving_email",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=30)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", max_length=255, null=True),
                ),
                ("balance", models.IntegerField(default=0)),
                ("credit_limit", models.IntegerField(default=0)),
                (
                    "tin_number",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "prz_number",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "vat_number",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=30)),
                ("registration_number", models.CharField(default="", max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("printer_name", models.CharField(max_length=30)),
                ("client_node", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=30)),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
