# Generated by Django 5.0.3 on 2025-01-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='branch_verification_key',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
