# Generated by Django 5.0.3 on 2025-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientsetting_branch_verification_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='branch_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
