# Generated by Django 5.0.3 on 2025-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientsetting_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='branch_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
