# Generated by Django 5.0.3 on 2025-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientsetting_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='sync_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='branch_id',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
