# Generated by Django 5.0.3 on 2025-01-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientsetting_sync_url_alter_clientsetting_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='sync_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
