# Generated by Django 5.0.3 on 2025-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientsetting_sync_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='last_sync_user',
            field=models.CharField(default='', max_length=300),
        ),
    ]
