# Generated by Django 5.0.3 on 2025-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clientsetting_last_sync_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='last_sync_date',
            field=models.CharField(default='', max_length=300),
        ),
    ]
