# Generated by Django 5.0.3 on 2025-01-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clientsetting_last_sync_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsetting',
            old_name='last_sync_date',
            new_name='last_sync_time',
        ),
    ]
