# Generated by Django 5.0.3 on 2025-01-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_last_sync_date_clientsetting_last_sync_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
