# Generated by Django 5.0.3 on 2025-01-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientsetting_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='branch_verification_key',
            field=models.CharField(default='', max_length=300),
        ),
    ]
