# Generated by Django 5.0.3 on 2025-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_clientsetting_branch_verification_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature_link',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
