# Generated by Django 5.0.3 on 2026-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_e_signature_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='ZW', max_length=50)),
                ('type', models.CharField(default='STORE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('branch_verification_key', models.CharField(default='', max_length=300)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_url', models.CharField(default='', max_length=300)),
                ('last_sync_time', models.CharField(default='', max_length=300)),
                ('last_sync_user', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
