# Generated by Django 5.0.3 on 2026-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customeraccount_created_by_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
