# Generated by Django 5.0.3 on 2026-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_branch_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Branch', max_length=100),
            preserve_default=False,
        ),
    ]
