# Generated by Django 5.0.3 on 2026-06-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
    ]
