# Generated by Django 5.0.3 on 2026-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default='Branch', max_length=100),
            preserve_default=False,
        ),
    ]
