# Generated by Django 5.0.3 on 2026-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='prz_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='tin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='vat_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
