# Generated by Django 5.0.3 on 2026-06-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customeraccount_prz_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/images/company'),
        ),
    ]
