# Generated by Django 5.0.3 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_clientsetting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='thank_you_message',
            field=models.TextField(blank=True, max_length=46, null=True),
        ),
    ]
