# Generated by Django 5.0.3 on 2026-07-24 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_clientsetting_thank_you_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.printercase'),
        ),
    ]
