# Generated by Django 5.0.3 on 2026-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_current_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank_1_account_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_1_bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_1_name_nostro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_1_name_zig',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='thank_you_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
