# Generated by Django 5.0.3 on 2026-07-31 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_branch_bank_1_account_name_branch_bank_1_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_verification_key',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='last_sync_user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='sync_url',
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
