# Generated by Django 5.0.3 on 2026-07-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_branch_branch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.IntegerField(default=1),
        ),
    ]
