# Generated by Django 5.0.3 on 2026-07-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_branch_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank_1_name_nostro',
            new_name='bank_1_nostro',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bank_1_name_zig',
            new_name='bank_1_zig',
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/company'),
        ),
    ]
