# Generated by Django 5.0.3 on 2026-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_bank_1_name_nostro_branch_bank_1_nostro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='creditnote_number_prefix',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clientsetting',
            name='quotation_number_prefix',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='invoice_number_prefix',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
