# Generated by Django 5.0.3 on 2026-07-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_clientsetting_creditnote_number_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='creditnote_number_prefix',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='invoice_number_prefix',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='quotation_number_prefix',
            field=models.CharField(default='', max_length=30),
        ),
    ]
