# Generated by Django 5.0.3 on 2026-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_clientsetting_creditnote_number_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_account_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_bank_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_name_nostro',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_name_zig',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='company_registration',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='configuration_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='expiration_warning',
            field=models.DecimalField(decimal_places=0, default=90, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='online_update_minute_intervals',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='prz_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='tel',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='tin_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='vat_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
