# Generated by Django 5.0.3 on 2026-08-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_branch_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_account_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_bank_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_name_nostro',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='bank_1_name_zig',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='branch_verification_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='company_registration',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='creditnote_number_prefix',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='hosting_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='hosting_email_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='invoice_number_prefix',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='last_sync_time',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='last_sync_user',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='notification_receiving_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='prz_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='quotation_number_prefix',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='sync_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='tin_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
