# Generated by Django 5.0.3 on 2026-08-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_clientsetting_bank_1_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
