# Generated by Django 5.0.3 on 2026-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_branch_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsetting',
            name='notification_receiving_email',
        ),
        migrations.AddField(
            model_name='clientsetting',
            name='notification_receiving_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
