# Generated by Django 5.0.3 on 2026-08-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_clientsetting_notification_receiving_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
