# Generated by Django 5.2.17 on 2026-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_user_address_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='prz_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='tin_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
