# Generated by Django 5.2.17 on 2026-09-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_customeraccount_prz_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='print_delay',
            field=models.IntegerField(default=5, help_text='Time delay when printing fiscal invoices to give time for sync (in sec)'),
        ),
    ]
