# Generated by Django 5.2.17 on 2026-09-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_clientsetting_print_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='e_signature_link',
        ),
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='e_signatures/'),
        ),
    ]
