# Generated by Django 5.0.3 on 2026-02-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_quotation_quotationitem_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.quotation'),
        ),
    ]
