# Generated by Django 5.0.3 on 2026-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_quotationitem_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
