# Generated by Django 5.0.3 on 2026-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_quotation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
