# Generated by Django 5.0.3 on 2026-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_quotation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
