# Generated by Django 5.0.3 on 2026-02-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_quotation_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='just_created',
            field=models.BooleanField(default=True),
        ),
    ]
