# Generated by Django 5.0.3 on 2026-02-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_e_signature_link'),
        ('pos', '0008_quotation_just_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customeraccount'),
        ),
    ]
