# Generated by Django 5.2.17 on 2026-09-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_alter_vatcode_default_hs_code'),
        ('pos', '0009_quotation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod'),
        ),
    ]
