# Generated by Django 5.2.17 on 2026-08-24 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Printer name (e.g., 'POS-90', 'TAJO POS')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the printer', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the printer location/use')),
                ('ip_address', models.GenericIPAddressField(help_text='Printer IP address on network')),
                ('port', models.PositiveIntegerField(default=9100, help_text='Printer port (usually 9100)')),
                ('printer_type', models.CharField(choices=[('thermal', 'Thermal'), ('laser', 'Laser'), ('inkjet', 'Inkjet'), ('dot_matrix', 'Dot Matrix'), ('receipt', 'Receipt Printer')], default='receipt', max_length=20)),
                ('model', models.CharField(blank=True, help_text='Printer model', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_status_check', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable this printer')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default printer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('successful_jobs', models.PositiveIntegerField(default=0)),
                ('failed_jobs', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_printers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrinterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('status_change', 'Status Change'), ('print_job', 'Print Job'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='print_out.printer')),
            ],
            options={
                'verbose_name': 'Printer Log',
                'verbose_name_plural': 'Printer Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., receipt number)', max_length=100)),
                ('printer_name_at_time', models.CharField(help_text='Printer name used at job creation', max_length=100)),
                ('print_type', models.CharField(default='full_receipt', max_length=20)),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('qr_data', models.CharField(blank=True, max_length=500)),
                ('footer', models.CharField(blank=True, max_length=500)),
                ('logo_data', models.TextField(blank=True, help_text='Base64 encoded logo')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Server'), ('spooled', 'In Windows Spooler'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Detailed status message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('spooled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('server_response', models.JSONField(blank=True, help_text='Response from Windows print server', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='print_out.printer')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='print_out_p_status_6e1360_idx'), models.Index(fields=['printer', 'status'], name='print_out_p_printer_c2524d_idx'), models.Index(fields=['reference'], name='print_out_p_referen_6772a3_idx')],
            },
        ),
    ]
