# Generated by Django 5.0.3 on 2026-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_out', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='port',
            field=models.PositiveIntegerField(default=9101, help_text='Printer port (usually 9101)'),
        ),
    ]
