# Generated by Django 5.2.17 on 2026-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_out', '0002_alter_printer_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printjob',
            name='printer',
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.RemoveField(
            model_name='printer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='failed_jobs',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='last_status_check',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='model',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='port',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='printer_type',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='successful_jobs',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='total_jobs',
        ),
        migrations.AddField(
            model_name='printer',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='server_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', help_text='IP address of the Windows computer running the print server'),
        ),
        migrations.AddField(
            model_name='printer',
            name='server_port',
            field=models.PositiveIntegerField(default=9101, help_text='Windows print server port'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly name shown in Clarity Retail', max_length=150),
        ),
        migrations.AlterField(
            model_name='printer',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(help_text='Exact Windows printer name, e.g. TAJO POS', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='PrinterLog',
        ),
        migrations.DeleteModel(
            name='PrintJob',
        ),
    ]
