# Generated by Django 5.2.17 on 2026-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_out', '0003_remove_printjob_created_by_remove_printjob_printer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='server_ip',
            field=models.CharField(default='127.0.0.1', help_text='IP address or hostname of the Windows computer running the print server', max_length=255),
        ),
    ]
