# Generated by Django 5.2.17 on 2026-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_out', '0006_alter_printer_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(help_text='Exact Windows printer name, e.g. POS-90', max_length=100, unique=True),
        ),
    ]
