# Generated by Django 5.0.3 on 2026-07-28 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalisation_enabled', models.BooleanField(default=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.CharField(blank=True, max_length=100)),
                ('pause_reason', models.TextField(blank=True)),
                ('allowed_currences', models.CharField(default='USD, ZWG', max_length=200)),
                ('api_base_url', models.CharField(default='https://Zimratest.samcima.com/api/Zimra', max_length=200)),
                ('qr_url', models.CharField(default='https://fdmstest.zimra.co.zw', help_text='QR URL from ZIMRA getConfig', max_length=200)),
                ('device_id', models.CharField(blank=True, help_text='Your ZIMRA Device ID', max_length=50)),
                ('machine_code', models.CharField(blank=True, help_text='Machine code provided by Binary Software', max_length=50)),
                ('api_password', models.CharField(blank=True, help_text='Password provided by Binary Software', max_length=100)),
                ('sync_interval_seconds', models.IntegerField(default=30)),
                ('max_retry_count', models.IntegerField(default=5)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('auto_resume_on_success', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscalisation Settings',
                'verbose_name_plural': 'Fiscalisation Settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_lines', models.JSONField(blank=True, default=list, help_text='List of payment methods and amounts')),
                ('line_items', models.JSONField(default=list)),
                ('doc_type', models.CharField(choices=[('FISCALINVOICE', 'Fiscal Invoice'), ('CREDITNOTE', 'Credit Note'), ('DEBITNOTE', 'Debit Note')], max_length=20)),
                ('inv_number', models.IntegerField(blank=True, null=True)),
                ('inv_number_global', models.IntegerField(blank=True, null=True)),
                ('doc_currency', models.CharField(default='USD', max_length=3)),
                ('my_yyy_mm_dd_date', models.DateField()),
                ('my_24hr_time_format_with_seconds', models.CharField(max_length=20)),
                ('document_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nontaxible_sales_amt_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('zero_per_taxamt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('zero_perc_sales_amt_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amt_15_perc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_15_perc_sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('machinecode', models.CharField(default='', max_length=10)),
                ('the_password', models.CharField(default='', max_length=10)),
                ('invoice_number_to_credit_debit', models.IntegerField(blank=True, null=True)),
                ('buyer_register_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyer_TIN', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('VAT_number', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('phone_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('local_receipt_number', models.IntegerField(blank=True, null=True)),
                ('local_invoice_number_to_credit_debit', models.IntegerField(blank=True, null=True)),
                ('binary_server_response', models.JSONField(blank=True, default=dict)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('PROCESSING', 'Processing...'), ('SYNCED', 'Synced to ZIMRA'), ('FAILED', 'Failed - Needs Retry'), ('BYPASSED', 'Bypassed - Fiscalisation was off'), ('VOID', 'Voided')], max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_receipt_number', models.IntegerField(default=0)),
                ('fiscal_receipt_global_no', models.IntegerField(default=0)),
                ('last_fiscal_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fiscal Receipt Sequence',
                'verbose_name_plural': 'Fiscal Receipt Sequences',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('synced_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('fiscal_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalreceipt')),
            ],
            options={
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['attempt_time'], name='fiscalisati_attempt_ed3e93_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('fiscal_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalreceipt')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for', 'locked_until'], name='fiscalisati_schedul_60bded_idx')],
            },
        ),
    ]
