# Generated by Django 5.0.3 on 2026-05-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('serial_no', models.CharField(max_length=100)),
                ('activation_key', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_day_no', models.IntegerField(default=1)),
                ('receipt_counter', models.IntegerField(default=1)),
                ('receipt_global_no', models.IntegerField(default=1)),
                ('is_day_open', models.BooleanField(default=False)),
                ('current_day_date', models.DateField(blank=True, null=True)),
                ('last_receipt_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('last_closed_day_no', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscaldevice')),
            ],
            options={
                'verbose_name_plural': 'Fiscal States',
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_global_no', models.IntegerField()),
                ('receipt_counter', models.IntegerField()),
                ('receipt_type', models.CharField(choices=[('FISCALINVOICE', 'Fiscal Invoice'), ('CREDITNOTE', 'Credit Note'), ('DEBITNOTE', 'Debit Note')], max_length=20)),
                ('invoice_no', models.CharField(max_length=100)),
                ('receipt_id', models.IntegerField(blank=True, null=True)),
                ('server_signature', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalstate')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_day_no', models.IntegerField()),
                ('day_date', models.DateField()),
                ('total_receipts', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_response', models.JSONField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalstate')),
            ],
            options={
                'unique_together': {('fiscal_state', 'fiscal_day_no')},
            },
        ),
    ]
