# Generated by Django 5.0.3 on 2026-05-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldaysummary',
            options={'verbose_name_plural': 'Fiscal Day Summaries'},
        ),
        migrations.RenameField(
            model_name='fiscaldaysummary',
            old_name='total_receipts',
            new_name='total_receipts_processed',
        ),
        migrations.RenameField(
            model_name='fiscaldaysummary',
            old_name='total_sales',
            new_name='total_sales_value',
        ),
        migrations.RenameField(
            model_name='fiscalreceipt',
            old_name='receipt_id',
            new_name='zimra_receipt_id',
        ),
        migrations.RenameField(
            model_name='fiscalreceipt',
            old_name='server_signature',
            new_name='zimra_response_log',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='fiscalstate',
            name='last_closed_day_no',
        ),
        migrations.AddField(
            model_name='fiscaldaysummary',
            name='closing_counters_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldaysummary',
            name='is_closed_successfully',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='cert_path',
            field=models.CharField(default='fiscalisation/certs/certificate.crt', max_length=255),
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='private_key_path',
            field=models.CharField(default='fiscalisation/certs/decrypted_key.key', max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='fiscal_day_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='local_hash',
            field=models.CharField(default='detyugihj;l', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='local_signature',
            field=models.TextField(default="srtyuiyui'l;"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='prepared_payload',
            field=models.JSONField(default={}, help_text='The exact JSON payload built by prepareReceipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='qr_code_string',
            field=models.TextField(default="rdfguihojpk;l'", help_text='Raw verification URL data used for offline QR prints'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('SUCCESS', 'Synced to ZIMRA'), ('FAILED', 'Rejected by ZIMRA')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='fiscal_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fiscalisation.fiscalstate'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='invoice_no',
            field=models.CharField(help_text='Local SaleTransaction ID reference', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('FISCALINVOICE', 'Fiscal Invoice'), ('CREDITNOTE', 'Credit Note'), ('DEBITNOTE', 'Debit Note')], default='FISCALINVOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalstate',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='fiscalisation.fiscaldevice'),
        ),
        migrations.AlterField(
            model_name='fiscalstate',
            name='receipt_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fiscalstate',
            name='receipt_global_no',
            field=models.IntegerField(default=0),
        ),
    ]
