# Generated by Django 5.0.3 on 2026-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalisationsettings',
            name='fiscalisation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
