# Generated by Django 5.0.3 on 2026-05-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0002_alter_fiscaldaysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalstate',
            name='day_opened_at',
            field=models.DateTimeField(blank=True, help_text="Wall-clock timestamp when openDay succeeded. Used to compute hours-open and warn before ZIMRA's max-hours cap.", null=True),
        ),
    ]
