# Generated by Django 5.0.3 on 2026-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0003_fiscalstate_day_opened_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('fiscalization_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_reason', models.CharField(blank=True, choices=[('zimra_down', 'ZIMRA / FDMS unreachable'), ('cert_expired', 'Certificate expired or invalid'), ('device_not_configured', 'Device not yet configured'), ('maintenance', 'Scheduled maintenance'), ('other', 'Other (see notes)')], default='', max_length=32)),
                ('paused_notes', models.TextField(blank=True, default='', help_text='Free-text reason — shown on the dashboard banner.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fiscal Settings',
            },
        ),
    ]
