# Generated by Django 5.0.3 on 2026-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0004_fiscalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ZIMRA Server', help_text='Server name/label', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one server can be active at a time')),
                ('test_api_url', models.CharField(default='https://fdmsapitest.zimra.co.zw', help_text='Test environment API URL (no trailing slash)', max_length=200)),
                ('prod_api_url', models.CharField(default='https://fdmsapi.zimra.co.zw', help_text='Production environment API URL (no trailing slash)', max_length=200)),
                ('test_qr_url', models.CharField(default='https://fdmstest.zimra.co.zw', help_text='Test environment QR/Receipt verification URL (no trailing slash)', max_length=200)),
                ('prod_qr_url', models.CharField(default='https://fdms.zimra.co.zw', help_text='Production environment QR/Receipt verification URL (no trailing slash)', max_length=200)),
                ('default_device_model_name', models.CharField(default='Server', help_text='Default device model name for this server', max_length=100)),
                ('default_device_model_version', models.CharField(default='1.0', help_text='Default device model version', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Server',
                'verbose_name_plural': 'Fiscal Servers',
                'db_table': 'fiscal_server',
            },
        ),
    ]
