# Generated by Django 5.0.3 on 2026-06-09 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0005_fiscalserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalisation_enabled', models.BooleanField(default=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.CharField(blank=True, max_length=100)),
                ('pause_reason', models.TextField(blank=True)),
                ('api_base_url', models.CharField(default='https://Zimratest.samcima.com/api', max_length=200)),
                ('api_password', models.CharField(blank=True, max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('sync_interval_seconds', models.IntegerField(default=30)),
                ('max_retry_count', models.IntegerField(default=5)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('auto_resume_on_success', models.BooleanField(default=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscalisation Settings',
                'verbose_name_plural': 'Fiscalisation Settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_receipt_number', models.IntegerField(default=0)),
                ('fiscal_receipt_global_no', models.IntegerField(default=0)),
                ('last_fiscal_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fiscal Receipt Sequence',
                'verbose_name_plural': 'Fiscal Receipt Sequences',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('synced_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-priority', 'scheduled_for'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='fiscaldaysummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fiscaldaysummary',
            name='fiscal_state',
        ),
        migrations.RemoveField(
            model_name='fiscalstate',
            name='device',
        ),
        migrations.DeleteModel(
            name='FiscalServer',
        ),
        migrations.DeleteModel(
            name='FiscalSettings',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='fiscal_state',
        ),
        migrations.AlterModelOptions(
            name='fiscalreceipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='fiscal_day_no',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='local_hash',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='local_signature',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='prepared_payload',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='qr_code_string',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='receipt_counter',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='receipt_global_no',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='zimra_receipt_id',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='zimra_response_log',
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='binary_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_tin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_vat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_global_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='internal_invoice_id',
            field=models.IntegerField(blank=True, help_text="Your POS system's invoice/transaction ID", null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='internal_invoice_number',
            field=models.CharField(default=1, help_text="Your POS system's invoice number (e.g., INV-001)", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='internal_sale_id',
            field=models.IntegerField(blank=True, help_text='Your SaleTransaction.id from your POS system', null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='original_fiscal_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='fiscalisation.fiscalreceipt'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='original_invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced to ZIMRA'), ('FAILED', 'Failed - Needs Retry'), ('BYPASSED', 'Bypassed - Fiscalisation was off'), ('VOID', 'Voided')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='tax_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='transaction_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['status', 'retry_count'], name='fiscalisati_status_716401_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['internal_invoice_number'], name='fiscalisati_interna_374fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['fiscal_receipt_number'], name='fiscalisati_fiscal__9e11d0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['created_at'], name='fiscalisati_created_805a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalreceipt',
            index=models.Index(fields=['status'], name='fiscalisati_status_b7542a_idx'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='fiscal_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalreceipt'),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='fiscal_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalisation.fiscalreceipt'),
        ),
        migrations.DeleteModel(
            name='FiscalDaySummary',
        ),
        migrations.DeleteModel(
            name='FiscalDevice',
        ),
        migrations.DeleteModel(
            name='FiscalState',
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['attempt_time'], name='fiscalisati_attempt_ed3e93_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['scheduled_for', 'locked_until'], name='fiscalisati_schedul_60bded_idx'),
        ),
    ]
