# Generated by Django 5.0.3 on 2026-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0006_fiscalisationsettings_fiscalreceiptsequence_synclog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalisationsettings',
            name='machine_code',
            field=models.CharField(blank=True, help_text='Machine code provided by Binary Software', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalisationsettings',
            name='api_password',
            field=models.CharField(blank=True, help_text='Password provided by Binary Software', max_length=100),
        ),
        migrations.AlterField(
            model_name='fiscalisationsettings',
            name='device_id',
            field=models.CharField(blank=True, help_text='Your ZIMRA Device ID', max_length=50),
        ),
    ]
