# Generated by Django 5.0.3 on 2026-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0007_fiscalisationsettings_machine_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalisationsettings',
            name='api_base_url',
            field=models.CharField(default='https://Zimratest.samcima.com/api/Zimra', max_length=200),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_sale_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
