# Generated by Django 5.0.3 on 2026-06-09 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0008_alter_fiscalisationsettings_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payments',
            field=models.JSONField(blank=True, default=list, help_text="List of payment methods and amounts - e.g., [{'method': 'CASH', 'amount': 100.00}]"),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='binary_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from Binary API'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_global_no',
            field=models.IntegerField(blank=True, help_text='Cumulative global number across all fiscal receipts', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_number',
            field=models.IntegerField(blank=True, help_text='Auto-incrementing fiscal receipt number (resets daily)', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_id',
            field=models.IntegerField(blank=True, help_text="Your POS system's invoice/transaction ID", null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_number',
            field=models.CharField(help_text="Your POS system's invoice number (e.g., INV-001)", max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_sale_id',
            field=models.IntegerField(blank=True, help_text='Your SaleTransaction.id from your POS system', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='line_items',
            field=models.JSONField(default=list, help_text='List of items sold - each item has description, quantity, price, total, tax info'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='original_fiscal_receipt',
            field=models.ForeignKey(blank=True, help_text='For credit notes: which original receipt is being credited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='fiscalisation.fiscalreceipt'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='original_invoice_number',
            field=models.CharField(blank=True, help_text='Original invoice number (for credit notes)', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='QR code URL from Binary API', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='tax_breakdown',
            field=models.JSONField(default=dict, help_text='Tax amounts by rate'),
        ),
    ]
