# Generated by Django 5.0.3 on 2026-06-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0009_fiscalreceipt_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='binary_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_global_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='internal_sale_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='original_fiscal_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='fiscalisation.fiscalreceipt'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='original_invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='payments',
            field=models.JSONField(blank=True, default=list, help_text='List of payment methods and amounts'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='tax_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
