# Generated by Django 5.0.3 on 2026-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0010_alter_fiscalreceipt_binary_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalisationsettings',
            name='qr_url',
            field=models.CharField(default='https://fdmstest.zimra.co.zw', help_text='QR URL for receipt verification - from ZIMRA getConfig', max_length=200),
        ),
    ]
