# Generated by Django 5.0.3 on 2026-06-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0012_fiscalreceipt_device_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalisationsettings',
            name='qr_url',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='device_signature',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='device_signature_hash',
        ),
    ]
