# Generated by Django 5.0.3 on 2026-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0013_remove_fiscalisationsettings_qr_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='device_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='device_signature_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
