# Generated by Django 5.0.3 on 2026-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0015_fiscalisationsettings_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceiptsequence',
            name='allowed_currences',
            field=models.CharField(default='USD, ZWG', max_length=200),
        ),
    ]
