# Generated by Django 5.0.3 on 2026-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0016_fiscalreceiptsequence_allowed_currences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalreceiptsequence',
            name='allowed_currences',
        ),
        migrations.AddField(
            model_name='fiscalisationsettings',
            name='allowed_currences',
            field=models.CharField(default='USD, ZWG', max_length=200),
        ),
    ]
