# Generated by Django 5.0.3 on 2026-07-06 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0017_remove_fiscalreceiptsequence_allowed_currences_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalreceipt',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='fiscalisati_status_716401_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='fiscalisati_interna_374fb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='fiscalisati_fiscal__9e11d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='fiscalisati_created_805a3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalreceipt',
            name='fiscalisati_status_b7542a_idx',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='binary_response',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_phone',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_tin',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='buyer_vat',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='device_signature',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='device_signature_hash',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_global_no',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='fiscal_receipt_number',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='internal_invoice_id',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='internal_invoice_number',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='internal_sale_id',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='original_fiscal_receipt',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='original_invoice_number',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='receipt_type',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='tax_breakdown',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='fiscalreceipt',
            name='transaction_time',
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='VAT_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='binary_server_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_register_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='doc_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='doc_type',
            field=models.CharField(choices=[('CREDITNOTE', 'Credit Note'), ('FISCALINVOICE', 'Fiscal Invoice'), ('DEBITNOTE', 'Debit Note')], default='fiscalreceipt', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='document_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='inv_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='invoice_number_to_credit_debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='local_invoice_number_to_credit_debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='local_receipt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='machinecode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='my_24hr_time_format_with_seconds',
            field=models.CharField(default=datetime.datetime(2026, 7, 6, 6, 43, 48, 205071, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='my_yyy_mm_dd_date',
            field=models.DateField(default=datetime.datetime(2026, 7, 6, 6, 43, 59, 584341, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='nontaxible_sales_amt_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payment_lines',
            field=models.JSONField(blank=True, default=list, help_text='List of payment methods and amounts'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='phone_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='tax_15_perc_sales_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='tax_amt_15_perc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='the_password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='zero_per_taxamt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='zero_perc_sales_amt_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced to ZIMRA'), ('VOID', 'Voided'), ('FAILED', 'Failed - Needs Retry')], max_length=20),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='buyer_TIN',
            field=models.CharField(default='', max_length=15),
        ),
    ]
