# Generated by Django 5.0.3 on 2026-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0018_alter_fiscalreceipt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='doc_type',
            field=models.CharField(choices=[('FISCALINVOICE', 'Fiscal Invoice'), ('CREDITNOTE', 'Credit Note'), ('DEBITNOTE', 'Debit Note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed - Needs Retry'), ('SYNCED', 'Synced to ZIMRA'), ('PENDING', 'Pending Sync'), ('VOID', 'Voided')], max_length=20),
        ),
    ]
