# Generated by Django 5.0.3 on 2026-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0019_alter_fiscalreceipt_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='inv_number_global',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced to ZIMRA'), ('FAILED', 'Failed - Needs Retry'), ('BYPASSED', 'Bypassed - Fiscalisation was off'), ('VOID', 'Voided')], max_length=20),
        ),
    ]
