# Generated by Django 5.0.3 on 2026-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalisation', '0020_fiscalreceipt_inv_number_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='VAT_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='buyer_TIN',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='buyer_register_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Sync'), ('PROCESSING', 'Processing...'), ('SYNCED', 'Synced to ZIMRA'), ('FAILED', 'Failed - Needs Retry'), ('BYPASSED', 'Bypassed - Fiscalisation was off'), ('VOID', 'Voided')], max_length=20),
        ),
    ]
