# Generated by Django 5.0.3 on 2024-09-18 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=40)),
                ("notification_type", models.CharField(default="", max_length=30)),
                ("detail", models.CharField(max_length=100)),
                ("status", models.CharField(default="New", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bar_code",
                    models.CharField(
                        blank=True, default="N/A", max_length=30, null=True
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "product_code",
                    models.CharField(
                        blank=True, default="N/A", max_length=50, null=True
                    ),
                ),
                ("details", models.TextField(default="", max_length=400)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnInn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(default="", max_length=255)),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_units", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(default="", max_length=255)),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_units", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shortcut", models.CharField(max_length=20)),
                ("details", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=4, default="0", max_digits=22),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=50,
                        max_digits=22,
                        null=True,
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(blank=True, default=100, null=True),
                ),
                ("expiration_warning_days", models.IntegerField(default=90)),
                ("status", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=40)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vat_price", models.DecimalField(decimal_places=4, max_digits=22)),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                ("total_packs", models.IntegerField(blank=True, null=True)),
                ("pack_size", models.IntegerField(blank=True, null=True)),
                (
                    "buying_pack_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "total_buying_pack_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("batch_number", models.CharField(max_length=40)),
                (
                    "discount_number",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                (
                    "selling_price_number",
                    models.DecimalField(decimal_places=4, default=0, max_digits=22),
                ),
                (
                    "selling_price_type",
                    models.CharField(default="SELLING PRICE", max_length=40),
                ),
                (
                    "discount_type",
                    models.CharField(default="DISCOUNT PRICE", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("total_packs", models.IntegerField(blank=True, null=True)),
                ("pack_size", models.IntegerField(blank=True, null=True)),
                ("total_units", models.IntegerField(blank=True, null=True)),
                (
                    "buying_pack_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                (
                    "VAT",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchAdjustmentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shortcut", models.CharField(max_length=20)),
                ("details", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(default="Subtract", max_length=10)),
                ("total_units", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enventory.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="enventory.batchadjustmentreason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=40)),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=22),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.supplier",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enventory.invoice"
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vat_price", models.DecimalField(decimal_places=4, max_digits=22)),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                ("total_packs", models.IntegerField(blank=True, null=True)),
                ("pack_size", models.IntegerField(blank=True, null=True)),
                (
                    "buying_pack_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "total_buying_pack_price",
                    models.DecimalField(decimal_places=4, max_digits=22),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=22, null=True
                    ),
                ),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("batch_number", models.CharField(max_length=40)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enventory.invoice",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
