# Generated by Django 5.0.3 on 2024-09-18 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("enventory", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.vatcode",
            ),
        ),
        migrations.AddField(
            model_name="returninn",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returninn",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.sale",
            ),
        ),
        migrations.AddField(
            model_name="returnout",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="enventory.batch",
            ),
        ),
        migrations.AddField(
            model_name="returnout",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returnreason",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returnout",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="enventory.returnreason",
            ),
        ),
        migrations.AddField(
            model_name="returninn",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="enventory.returnreason",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="enventory.product"
            ),
        ),
        migrations.AddField(
            model_name="returninn",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="enventory.stock",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enventory.stock",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="enventory.stock"
            ),
        ),
        migrations.AddField(
            model_name="temporaryinvoice",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="temporaryinvoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="accounts.supplier"
            ),
        ),
        migrations.AddField(
            model_name="temporaryinvoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enventory.temporaryinvoice",
            ),
        ),
        migrations.AddField(
            model_name="temporaryinvoiceitem",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="temporaryinvoiceitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enventory.stock",
            ),
        ),
    ]
