# Generated by Django 5.0.3 on 2024-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="reorder_quantity",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
