# Generated by Django 5.0.3 on 2026-04-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0003_alter_stock_reorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninn',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
