# Generated by Django 5.0.3 on 2026-04-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0005_creditnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninn',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='returninn',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='returninn',
            name='refund_amount',
        ),
    ]
