# Generated by Django 5.0.3 on 2026-04-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0006_remove_returninn_notes_remove_returninn_reason_and_more'),
        ('payments', '0013_alter_expensemoneyportion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='sale_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.saletransaction'),
        ),
    ]
