# Generated by Django 5.0.3 on 2026-04-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0007_creditnote_sale_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninn',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enventory.creditnote'),
        ),
    ]
