# Generated by Django 5.0.3 on 2026-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0008_returninn_credit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
