# Generated by Django 5.0.3 on 2026-04-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0009_returninn_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returninn',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enventory.returnreason'),
        ),
    ]
