# Generated by Django 5.0.3 on 2026-05-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0010_returninn_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returninn',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='returninn',
            name='refund_amount',
        ),
    ]
