# Generated by Django 5.0.3 on 2026-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0012_add_global_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='batchadjustment',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='batchadjustmentreason',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='returninn',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='returnout',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='returnreason',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='global_id',
        ),
        migrations.AddField(
            model_name='product',
            name='branch_created',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='branch_updated',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_synced',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='global_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
