# Generated by Django 5.0.3 on 2026-05-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customeraccount_created_by_branch_and_more'),
        ('enventory', '0013_remove_batch_global_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batchadjustment',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='batchadjustmentreason',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='returninn',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returninn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returninn',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='returninn',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returninn',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='returninn',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returninn',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='returnout',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returnout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnout',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='returnout',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnout',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='returnout',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returnout',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
