# Generated by Django 5.0.3 on 2026-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0014_batch_created_by_branch_batch_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='global_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
