# Generated by Django 5.0.3 on 2026-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0015_alter_product_global_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zimra_hs_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
