# Generated by Django 5.0.3 on 2026-06-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_clientsetting_thank_you_message'),
        ('enventory', '0016_product_zimra_hs_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('needs_sync', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('branch_created', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('branch_updated', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_synced', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch')),
                ('updated_by_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enventory.category'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('needs_sync', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('branch_created', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('branch_updated', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_synced', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)s_records', to='accounts.branch')),
                ('updated_by_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)s_records', to='accounts.branch')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enventory.department'),
        ),
    ]
