# Generated by Django 5.0.3 on 2026-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enventory', '0018_alter_category_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
