# Generated by Django 5.0.3 on 2026-07-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_syncmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmanager',
            name='sync_intervals_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
