# Generated by Django 5.0.3 on 2026-07-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_syncmanager_sync_intervals_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_email', models.CharField(max_length=30)),
                ('hosting_email_password', models.CharField(max_length=255)),
                ('notification_receiving_emails', models.JSONField(blank=True, default=list)),
                ('stock_expiration_warning_days', models.IntegerField(default=60)),
            ],
        ),
    ]
