# Generated by Django 5.0.3 on 2026-07-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_notificationsmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProfile',
            new_name='SubscriptionManager',
        ),
    ]
