# Generated by Django 5.0.3 on 2026-07-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_orderprofile_subscriptionmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionmanager',
            old_name='payment_instructions',
            new_name='instructions',
        ),
    ]
