# Generated by Django 5.0.3 on 2026-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_payment_instructions_subscriptionmanager_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Avail Technologies Pvt Ltd', max_length=30)),
                ('website', models.CharField(default='www.avail.co.zw', max_length=30)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('support_call', models.CharField(default='+263 78 485 1863', max_length=255)),
                ('support_whatsapp', models.CharField(default='+263 78 610 6154', max_length=255)),
                ('support_email', models.CharField(default='info@avail.co.zw', max_length=255)),
                ('virsion', models.CharField(default=2.0, max_length=20)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
